version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: drive-ooblik-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-drive_ooblik}
      POSTGRES_USER: ${DB_USER:-ooblik}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - drive-ooblik-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-ooblik} -d ${DB_NAME:-drive_ooblik}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: drive-ooblik-api
    restart: unless-stopped
    environment:
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-drive_ooblik}
      DB_USER: ${DB_USER:-ooblik}
      DB_PASSWORD: ${DB_PASSWORD:-changeme}

      # Backend
      NODE_ENV: production
      PORT: 3001
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3001}

      # JWT
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      JWT_EXPIRES_IN: 4h
      JWT_ADMIN_EXPIRES_IN: 24h

      # Security
      BCRYPT_ROUNDS: 12
      RATE_LIMIT_WINDOW_MS: 3600000
      RATE_LIMIT_MAX_REQUESTS: 5

      # SMTP (optionnel)
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

      # S3 (optionnel)
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_REGION: ${S3_REGION:-eu-west-1}
      S3_BUCKET: ${S3_BUCKET}

      # hCaptcha
      HCAPTCHA_SECRET_KEY: ${HCAPTCHA_SECRET_KEY}

      # Frontend URL
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}

    depends_on:
      postgres:
        condition: service_healthy

    expose:
      - "3001"

    volumes:
      - app_logs:/app/logs

    networks:
      - drive-ooblik-network

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Web
  web:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
        VITE_HCAPTCHA_SITE_KEY: ${VITE_HCAPTCHA_SITE_KEY:-10000000-ffff-ffff-ffff-000000000001}
        VITE_DEV_MODE: ${VITE_DEV_MODE:-false}
    container_name: drive-ooblik-web
    restart: unless-stopped

    depends_on:
      - api

    ports:
      - "${APP_PORT:-80}:80"

    networks:
      - drive-ooblik-network

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Nginx Reverse Proxy (optionnel, pour SSL/proxy externe)
  nginx:
    image: nginx:alpine
    container_name: drive-ooblik-proxy
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - web
      - api
    networks:
      - drive-ooblik-network
    profiles:
      - with-proxy

# Volumes persistants
volumes:
  postgres_data:
    driver: local
    name: drive-ooblik-postgres
  app_logs:
    driver: local
    name: drive-ooblik-logs
  nginx_certs:
    driver: local
    name: drive-ooblik-certs
  nginx_vhost:
    driver: local
    name: drive-ooblik-vhost
  nginx_html:
    driver: local
    name: drive-ooblik-html

# Réseau privé
networks:
  drive-ooblik-network:
    driver: bridge
    name: drive-ooblik-net